### PR TITLE
update

### PR DESCRIPTION
**Pull request by LinguList**
The code now runs with my computer (one needs to have foma installed).

### CODE REVIEW

**Comment by LinguList** [comment]
in fact, I remembered: Lingrex added a check that was not there before. So we caught one erroneous annotation in the data, due to this check, which we ignored before (!).

**Comment by LinguList** [comment]
But it was only one case.

**Comment by LinguList** [comment]
Let me know if there are questions on my changes.

**Comment by knightss27** [comment]
Thanks so much! That is great to know, and it makes sense what you've done to get around that. I will try this out and let you know if I have any further questions.

**Pull request merged**
